# Use a PHP-specific image because the PHP packaging is garbage and takes a very
# long time to install.
FROM php:8.2-cli
RUN apt update
RUN apt install -y git
RUN git clone https://github.com/phoronix-test-suite/phoronix-test-suite.git
RUN git -C phoronix-test-suite checkout 99c30505d730c2429ad2120346dc197cf3f1355c
# For debug:
RUN apt install -y bash
COPY pts-config/test-suites /var/lib/phoronix-test-suite/test-suites
RUN /phoronix-test-suite/phoronix-test-suite batch-install fio
# Needs to happen after batch-install as it disables networking.
COPY pts-config/user-config.xml /etc/phoronix-test-suite.xml
ENV TEST_RESULTS_NAME=pts-results
CMD /phoronix-test-suite/phoronix-test-suite batch-run fio-suite && /phoronix-test-suite/phoronix-test-suite result-file-to-json pts-results